export const GET_ALL_FOOD = "GET_ALL_FOOD";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY"
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY"
export const CREATE_NEW_FOOD = "CREATE_NEW_FOOD";
export const REMOVE_FOOD = "REMOVE_FOOD";
export const SET_FOOD_LIST = "SET_FOOD_LIST";
export const GET_FOOD_LIST = "GET_FOOD_LIST";